export const FETCH_LAPTOPS_START = 'FETCH_LAPTOPS_START';
export const FETCH_LAPTOPS_SUCCESS = 'FETCH_LAPTOPS_SUCCESS';
export const FETCH_LAPTOPS_FAILED = 'FETCH_LAPTOPS_FAILED';
export const SET_LAPTOPS = 'SET_LAPTOPS';